-- Run this script in Supabase Dashboard -> SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Anonym bruger',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.drive_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  max_speed numeric(7,2) not null default 0 check (max_speed >= 0),
  distance_km numeric(10,3) not null default 0 check (distance_km >= 0),
  fines_avoided integer not null default 0 check (fines_avoided >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.drive_logs enable row level security;

create policy "Profiles are publicly readable"
  on public.profiles for select using (true);
create policy "Users can update their own profile"
  on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users can insert their own profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can insert their own drive logs"
  on public.drive_logs for insert with check (auth.uid() = user_id);
create policy "Users can read their own drive logs"
  on public.drive_logs for select using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), 'Anonym bruger'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace view public.leaderboard as
select
  p.id,
  p.display_name,
  count(d.id)::integer as trip_count,
  count(d.id) filter (where d.fines_avoided = 0)::integer as safe_trip_count,
  coalesce(sum(d.distance_km), 0)::numeric as total_distance_km,
  coalesce(sum(d.fines_avoided), 0)::integer as total_fines_avoided
from public.profiles p
left join public.drive_logs d on d.user_id = p.id
group by p.id, p.display_name;

grant select on public.leaderboard to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.drive_logs to authenticated;
